#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
FileCopy, temp_flag.tga, TWO_people.tga, 1
FileCopy, temp_flag.tga, CES_people.tga, 1
FileCopy, temp_flag.tga, TRL_people.tga, 1
FileCopy, temp_flag.tga, KLA_people.tga, 1
FileCopy, temp_flag.tga, VIP_people.tga, 1
FileCopy, temp_flag.tga, SCO_people.tga, 1
FileCopy, temp_flag.tga, NCN_people.tga, 1
FileCopy, temp_flag.tga, TWI_people.tga, 1
FileCopy, temp_flag.tga, WBH_people.tga, 1
FileCopy, temp_flag.tga, WHT_people.tga, 1
FileCopy, temp_flag.tga, RBD_people.tga, 1
FileCopy, temp_flag.tga, TOC_people.tga, 1
FileCopy, temp_flag.tga, RPD_people.tga, 1
FileCopy, temp_flag.tga, FOR_people.tga, 1
FileCopy, temp_flag.tga, CHE_people.tga, 1
FileCopy, temp_flag.tga, YMP_people.tga, 1
FileCopy, temp_flag.tga, MLT_people.tga, 1
FileCopy, temp_flag.tga, BRK_people.tga, 1
FileCopy, temp_flag.tga, NCS_people.tga, 1
FileCopy, temp_flag.tga, NAV_people.tga, 1
FileCopy, temp_flag.tga, ISN_people.tga, 1
FileCopy, temp_flag.tga, TLO_people.tga, 1
FileCopy, temp_flag.tga, COW_people.tga, 1
FileCopy, temp_flag.tga, MUR_people.tga, 1
FileCopy, temp_flag.tga, PMR_people.tga, 1
FileCopy, temp_flag.tga, TTM_people.tga, 1
FileCopy, temp_flag.tga, ARR_people.tga, 1
FileCopy, temp_flag.tga, EHT_people.tga, 1
FileCopy, temp_flag.tga, SHI_people.tga, 1
FileCopy, temp_flag.tga, SOR_people.tga, 1
FileCopy, temp_flag.tga, MOJ_people.tga, 1
FileCopy, temp_flag.tga, BEL_people.tga, 1
FileCopy, temp_flag.tga, DAM_people.tga, 1
FileCopy, temp_flag.tga, HAN_people.tga, 1
FileCopy, temp_flag.tga, BVC_people.tga, 1
FileCopy, temp_flag.tga, CHY_people.tga, 1
FileCopy, temp_flag.tga, BDT_people.tga, 1
FileCopy, temp_flag.tga, TON_people.tga, 1
FileCopy, temp_flag.tga, DEA_people.tga, 1
FileCopy, temp_flag.tga, PNT_people.tga, 1
FileCopy, temp_flag.tga, ZDW_people.tga, 1
FileCopy, temp_flag.tga, SCP_people.tga, 1
FileCopy, temp_flag.tga, ORI_people.tga, 1
FileCopy, temp_flag.tga, LOS_people.tga, 1
FileCopy, temp_flag.tga, MDT_people.tga, 1
FileCopy, temp_flag.tga, DES_people.tga, 1
FileCopy, temp_flag.tga, JAC_people.tga, 1
FileCopy, temp_flag.tga, RID_people.tga, 1
FileCopy, temp_flag.tga, GDH_people.tga, 1
FileCopy, temp_flag.tga, UMB_people.tga, 1
FileCopy, temp_flag.tga, IRN_people.tga, 1
FileCopy, temp_flag.tga, SPR_people.tga, 1
FileCopy, temp_flag.tga, TCA_people.tga, 1
FileCopy, temp_flag.tga, YAK_people.tga, 1
FileCopy, temp_flag.tga, BMT_people.tga, 1
FileCopy, temp_flag.tga, PEC_people.tga, 1
FileCopy, temp_flag.tga, RST_people.tga, 1
FileCopy, temp_flag.tga, TAR_people.tga, 1
FileCopy, temp_flag.tga, LON_people.tga, 1
FileCopy, temp_flag.tga, YEL_people.tga, 1
FileCopy, temp_flag.tga, NEW_people.tga, 1
FileCopy, temp_flag.tga, TOI_people.tga, 1
FileCopy, temp_flag.tga, RAM_people.tga, 1
FileCopy, temp_flag.tga, HIN_people.tga, 1
FileCopy, temp_flag.tga, RVR_people.tga, 1
FileCopy, temp_flag.tga, RBT_people.tga, 1
FileCopy, temp_flag.tga, VLT_people.tga, 1
FileCopy, temp_flag.tga, BLP_people.tga, 1
FileCopy, temp_flag.tga, ANT_people.tga, 1
FileCopy, temp_flag.tga, CRZ_people.tga, 1
FileCopy, temp_flag.tga, BPT_people.tga, 1
FileCopy, temp_flag.tga, BLA_people.tga, 1
FileCopy, temp_flag.tga, TOB_people.tga, 1
FileCopy, temp_flag.tga, NAM_people.tga, 1
FileCopy, temp_flag.tga, ORG_people.tga, 1
FileCopy, temp_flag.tga, POW_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TWO_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/CES_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TRL_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/KLA_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/VIP_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/SCO_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/NCN_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BOS_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TWI_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/WBH_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/WHT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/RBD_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TOC_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/RPD_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/FOR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/CHE_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/YMP_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/MLT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BRK_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/NCS_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/NAV_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/ISN_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TLO_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/COW_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/MUR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/PMR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TTM_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/ARR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/EHT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/SHI_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/SOR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/MOJ_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/KHA_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BEL_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/DAM_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/HAN_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BVC_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/CHY_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BDT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TON_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/DEA_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/PNT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/ZDW_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/SCP_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/ORI_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/LOS_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/MDT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/DES_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/JAC_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/RID_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/GDH_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/UMB_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/IRN_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/SPR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TCA_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/YAK_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BMT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/PEC_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/RST_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TAR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/LON_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/YEL_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/NEW_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TOI_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/RAM_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/HIN_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/RVR_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/RBT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/VLT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BLP_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/ANT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/CRZ_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BPT_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/BLA_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/TOB_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/NAM_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/ORG_people.tga, 1
FileCopy, medium_temp_flag.tga, medium/POW_people.tga, 1
FileCopy, small_temp_flag.tga, small/TWO_people.tga, 1
FileCopy, small_temp_flag.tga, small/CES_people.tga, 1
FileCopy, small_temp_flag.tga, small/TRL_people.tga, 1
FileCopy, small_temp_flag.tga, small/KLA_people.tga, 1
FileCopy, small_temp_flag.tga, small/VIP_people.tga, 1
FileCopy, small_temp_flag.tga, small/SCO_people.tga, 1
FileCopy, small_temp_flag.tga, small/NCN_people.tga, 1
FileCopy, small_temp_flag.tga, small/BOS_people.tga, 1
FileCopy, small_temp_flag.tga, small/TWI_people.tga, 1
FileCopy, small_temp_flag.tga, small/WBH_people.tga, 1
FileCopy, small_temp_flag.tga, small/WHT_people.tga, 1
FileCopy, small_temp_flag.tga, small/RBD_people.tga, 1
FileCopy, small_temp_flag.tga, small/TOC_people.tga, 1
FileCopy, small_temp_flag.tga, small/RPD_people.tga, 1
FileCopy, small_temp_flag.tga, small/FOR_people.tga, 1
FileCopy, small_temp_flag.tga, small/CHE_people.tga, 1
FileCopy, small_temp_flag.tga, small/YMP_people.tga, 1
FileCopy, small_temp_flag.tga, small/MLT_people.tga, 1
FileCopy, small_temp_flag.tga, small/BRK_people.tga, 1
FileCopy, small_temp_flag.tga, small/NCS_people.tga, 1
FileCopy, small_temp_flag.tga, small/NAV_people.tga, 1
FileCopy, small_temp_flag.tga, small/ISN_people.tga, 1
FileCopy, small_temp_flag.tga, small/TLO_people.tga, 1
FileCopy, small_temp_flag.tga, small/COW_people.tga, 1
FileCopy, small_temp_flag.tga, small/MUR_people.tga, 1
FileCopy, small_temp_flag.tga, small/PMR_people.tga, 1
FileCopy, small_temp_flag.tga, small/TTM_people.tga, 1
FileCopy, small_temp_flag.tga, small/ARR_people.tga, 1
FileCopy, small_temp_flag.tga, small/EHT_people.tga, 1
FileCopy, small_temp_flag.tga, small/SHI_people.tga, 1
FileCopy, small_temp_flag.tga, small/SOR_people.tga, 1
FileCopy, small_temp_flag.tga, small/MOJ_people.tga, 1
FileCopy, small_temp_flag.tga, small/KHA_people.tga, 1
FileCopy, small_temp_flag.tga, small/DAM_people.tga, 1
FileCopy, small_temp_flag.tga, small/HAN_people.tga, 1
FileCopy, small_temp_flag.tga, small/BVC_people.tga, 1
FileCopy, small_temp_flag.tga, small/CHY_people.tga, 1
FileCopy, small_temp_flag.tga, small/BDT_people.tga, 1
FileCopy, small_temp_flag.tga, small/TON_people.tga, 1
FileCopy, small_temp_flag.tga, small/DEA_people.tga, 1
FileCopy, small_temp_flag.tga, small/PNT_people.tga, 1
FileCopy, small_temp_flag.tga, small/ZDW_people.tga, 1
FileCopy, small_temp_flag.tga, small/SCP_people.tga, 1
FileCopy, small_temp_flag.tga, small/ORI_people.tga, 1
FileCopy, small_temp_flag.tga, small/LOS_people.tga, 1
FileCopy, small_temp_flag.tga, small/MDT_people.tga, 1
FileCopy, small_temp_flag.tga, small/DES_people.tga, 1
FileCopy, small_temp_flag.tga, small/JAC_people.tga, 1
FileCopy, small_temp_flag.tga, small/RID_people.tga, 1
FileCopy, small_temp_flag.tga, small/GDH_people.tga, 1
FileCopy, small_temp_flag.tga, small/UMB_people.tga, 1
FileCopy, small_temp_flag.tga, small/IRN_people.tga, 1
FileCopy, small_temp_flag.tga, small/TCA_people.tga, 1
FileCopy, small_temp_flag.tga, small/YAK_people.tga, 1
FileCopy, small_temp_flag.tga, small/BMT_people.tga, 1
FileCopy, small_temp_flag.tga, small/PEC_people.tga, 1
FileCopy, small_temp_flag.tga, small/RST_people.tga, 1
FileCopy, small_temp_flag.tga, small/TAR_people.tga, 1
FileCopy, small_temp_flag.tga, small/LON_people.tga, 1
FileCopy, small_temp_flag.tga, small/YEL_people.tga, 1
FileCopy, small_temp_flag.tga, small/NEW_people.tga, 1
FileCopy, small_temp_flag.tga, small/TOI_people.tga, 1
FileCopy, small_temp_flag.tga, small/RAM_people.tga, 1
FileCopy, small_temp_flag.tga, small/HIN_people.tga, 1
FileCopy, small_temp_flag.tga, small/RVR_people.tga, 1
FileCopy, small_temp_flag.tga, small/RBT_people.tga, 1
FileCopy, small_temp_flag.tga, small/VLT_people.tga, 1
FileCopy, small_temp_flag.tga, small/BLP_people.tga, 1
FileCopy, small_temp_flag.tga, small/ANT_people.tga, 1
FileCopy, small_temp_flag.tga, small/CRZ_people.tga, 1
FileCopy, small_temp_flag.tga, small/BPT_people.tga, 1
FileCopy, small_temp_flag.tga, small/BLA_people.tga, 1
FileCopy, small_temp_flag.tga, small/TOB_people.tga, 1
FileCopy, small_temp_flag.tga, small/NAM_people.tga, 1
FileCopy, small_temp_flag.tga, small/ORG_people.tga, 1
FileCopy, small_temp_flag.tga, small/POW_people.tga, 1
FileCopy, small_temp_flag.tga, small/TWO_people.tga, 1
FileCopy, small_temp_flag.tga, small/CES_people.tga, 1
FileCopy, small_temp_flag.tga, small/TRL_people.tga, 1
FileCopy, small_temp_flag.tga, small/KLA_people.tga, 1
FileCopy, small_temp_flag.tga, small/VIP_people.tga, 1
FileCopy, small_temp_flag.tga, small/SCO_people.tga, 1
FileCopy, small_temp_flag.tga, small/NCN_people.tga, 1
FileCopy, small_temp_flag.tga, small/BOS_people.tga, 1
FileCopy, small_temp_flag.tga, small/TWI_people.tga, 1
FileCopy, small_temp_flag.tga, small/WBH_people.tga, 1
FileCopy, small_temp_flag.tga, small/WHT_people.tga, 1
FileCopy, small_temp_flag.tga, small/RBD_people.tga, 1
FileCopy, small_temp_flag.tga, small/TOC_people.tga, 1
FileCopy, small_temp_flag.tga, small/RPD_people.tga, 1
FileCopy, small_temp_flag.tga, small/FOR_people.tga, 1
FileCopy, small_temp_flag.tga, small/CHE_people.tga, 1
FileCopy, small_temp_flag.tga, small/YMP_people.tga, 1
FileCopy, small_temp_flag.tga, small/MLT_people.tga, 1
FileCopy, small_temp_flag.tga, small/BRK_people.tga, 1
FileCopy, small_temp_flag.tga, small/NCS_people.tga, 1
FileCopy, small_temp_flag.tga, small/NAV_people.tga, 1
FileCopy, small_temp_flag.tga, small/ISN_people.tga, 1
FileCopy, small_temp_flag.tga, small/TLO_people.tga, 1
FileCopy, small_temp_flag.tga, small/COW_people.tga, 1
FileCopy, small_temp_flag.tga, small/MUR_people.tga, 1
FileCopy, small_temp_flag.tga, small/PMR_people.tga, 1
FileCopy, small_temp_flag.tga, small/TTM_people.tga, 1
FileCopy, small_temp_flag.tga, small/ARR_people.tga, 1
FileCopy, small_temp_flag.tga, small/EHT_people.tga, 1
FileCopy, small_temp_flag.tga, small/SHI_people.tga, 1
FileCopy, small_temp_flag.tga, small/SOR_people.tga, 1
FileCopy, small_temp_flag.tga, small/MOJ_people.tga, 1
FileCopy, small_temp_flag.tga, small/KHA_people.tga, 1
FileCopy, small_temp_flag.tga, small/DAM_people.tga, 1
FileCopy, small_temp_flag.tga, small/HAN_people.tga, 1
FileCopy, small_temp_flag.tga, small/BVC_people.tga, 1
FileCopy, small_temp_flag.tga, small/CHY_people.tga, 1
FileCopy, small_temp_flag.tga, small/BDT_people.tga, 1
FileCopy, small_temp_flag.tga, small/TON_people.tga, 1
FileCopy, small_temp_flag.tga, small/DEA_people.tga, 1
FileCopy, small_temp_flag.tga, small/PNT_people.tga, 1
FileCopy, small_temp_flag.tga, small/ZDW_people.tga, 1
FileCopy, small_temp_flag.tga, small/SCP_people.tga, 1
FileCopy, small_temp_flag.tga, small/ORI_people.tga, 1
FileCopy, small_temp_flag.tga, small/LOS_people.tga, 1
FileCopy, small_temp_flag.tga, small/MDT_people.tga, 1
FileCopy, small_temp_flag.tga, small/DES_people.tga, 1
FileCopy, small_temp_flag.tga, small/JAC_people.tga, 1
FileCopy, small_temp_flag.tga, small/RID_people.tga, 1
FileCopy, small_temp_flag.tga, small/GDH_people.tga, 1
FileCopy, small_temp_flag.tga, small/UMB_people.tga, 1
FileCopy, small_temp_flag.tga, small/IRN_people.tga, 1
FileCopy, small_temp_flag.tga, small/TCA_people.tga, 1
FileCopy, small_temp_flag.tga, small/YAK_people.tga, 1
FileCopy, small_temp_flag.tga, small/BMT_people.tga, 1
FileCopy, small_temp_flag.tga, small/PEC_people.tga, 1
FileCopy, small_temp_flag.tga, small/RST_people.tga, 1
FileCopy, small_temp_flag.tga, small/TAR_people.tga, 1
FileCopy, small_temp_flag.tga, small/LON_people.tga, 1
FileCopy, small_temp_flag.tga, small/YEL_people.tga, 1
FileCopy, small_temp_flag.tga, small/NEW_people.tga, 1
FileCopy, small_temp_flag.tga, small/TOI_people.tga, 1
FileCopy, small_temp_flag.tga, small/RAM_people.tga, 1
FileCopy, small_temp_flag.tga, small/HIN_people.tga, 1
FileCopy, small_temp_flag.tga, small/RVR_people.tga, 1
FileCopy, small_temp_flag.tga, small/RBT_people.tga, 1
FileCopy, small_temp_flag.tga, small/VLT_people.tga, 1
FileCopy, small_temp_flag.tga, small/BLP_people.tga, 1
FileCopy, small_temp_flag.tga, small/ANT_people.tga, 1
FileCopy, small_temp_flag.tga, small/CRZ_people.tga, 1
FileCopy, small_temp_flag.tga, small/BPT_people.tga, 1
FileCopy, small_temp_flag.tga, small/BLA_people.tga, 1
FileCopy, small_temp_flag.tga, small/TOB_people.tga, 1
FileCopy, small_temp_flag.tga, small/NAM_people.tga, 1
FileCopy, small_temp_flag.tga, small/ORG_people.tga, 1
FileCopy, small_temp_flag.tga, small/POW_people.tga, 1
FileCopy, ruler_temp_flag.tga, TWO_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, CES_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TRL_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, KLA_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, VIP_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, SCO_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, NCN_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TWI_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, WBH_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, WHT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, RBD_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TOC_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, RPD_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, FOR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, CHE_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, YMP_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, MLT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BRK_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, NCS_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, NAV_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, ISN_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TLO_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, COW_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, MUR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, PMR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TTM_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, ARR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, EHT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, SHI_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, SOR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, MOJ_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BEL_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, DAM_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, HAN_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BVC_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, CHY_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BDT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TON_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, DEA_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, PNT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, ZDW_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, SCP_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, ORI_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, LOS_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, MDT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, DES_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, JAC_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, RID_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, GDH_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, UMB_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, IRN_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, SPR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TCA_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, YAK_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BMT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, PEC_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, RST_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TAR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, LON_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, YEL_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, NEW_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TOI_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, RAM_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, HIN_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, RVR_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, RBT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, VLT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BLP_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, ANT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, CRZ_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BPT_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, BLA_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, TOB_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, NAM_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, ORG_ruler.tga, 1
FileCopy, ruler_temp_flag.tga, POW_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TWO_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/CES_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TRL_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/KLA_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/VIP_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/SCO_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/NCN_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BOS_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TWI_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/WBH_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/WHT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/RBD_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TOC_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/RPD_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/FOR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/CHE_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/YMP_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/MLT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BRK_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/NCS_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/NAV_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/ISN_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TLO_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/COW_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/MUR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/PMR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TTM_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/ARR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/EHT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/SHI_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/SOR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/MOJ_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/KHA_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BEL_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/DAM_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/HAN_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BVC_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/CHY_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BDT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TON_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/DEA_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/PNT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/ZDW_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/SCP_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/ORI_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/LOS_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/MDT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/DES_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/JAC_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/RID_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/GDH_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/UMB_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/IRN_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/SPR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TCA_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/YAK_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BMT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/PEC_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/RST_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TAR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/LON_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/YEL_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/NEW_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TOI_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/RAM_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/HIN_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/RVR_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/RBT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/VLT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BLP_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/ANT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/CRZ_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BPT_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/BLA_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/TOB_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/NAM_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/ORG_ruler.tga, 1
FileCopy, ruler_medium_temp_flag.tga, medium/POW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TWO_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CES_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TRL_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/KLA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/VIP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SCO_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NCN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BOS_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TWI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/WBH_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/WHT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RBD_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TOC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RPD_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/FOR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CHE_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/YMP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MLT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BRK_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NCS_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NAV_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ISN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TLO_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/COW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MUR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/PMR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TTM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ARR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/EHT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SHI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SOR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MOJ_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/KHA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/DAM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/HAN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BVC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CHY_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BDT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TON_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/DEA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/PNT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ZDW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SCP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ORI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/LOS_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MDT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/DES_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/JAC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RID_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/GDH_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/UMB_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/IRN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TCA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/YAK_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BMT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/PEC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RST_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TAR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/LON_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/YEL_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NEW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TOI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RAM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/HIN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RVR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RBT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/VLT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BLP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ANT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CRZ_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BPT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BLA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TOB_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NAM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ORG_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/POW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TWO_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CES_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TRL_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/KLA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/VIP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SCO_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NCN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BOS_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TWI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/WBH_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/WHT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RBD_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TOC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RPD_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/FOR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CHE_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/YMP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MLT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BRK_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NCS_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NAV_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ISN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TLO_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/COW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MUR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/PMR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TTM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ARR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/EHT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SHI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SOR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MOJ_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/KHA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/DAM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/HAN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BVC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CHY_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BDT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TON_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/DEA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/PNT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ZDW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/SCP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ORI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/LOS_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/MDT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/DES_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/JAC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RID_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/GDH_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/UMB_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/IRN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TCA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/YAK_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BMT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/PEC_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RST_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TAR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/LON_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/YEL_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NEW_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TOI_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RAM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/HIN_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RVR_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/RBT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/VLT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BLP_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ANT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/CRZ_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BPT_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/BLA_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/TOB_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/NAM_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/ORG_ruler.tga, 1
FileCopy, ruler_small_temp_flag.tga, small/POW_ruler.tga, 1