NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999
NDefines.NMilitary.LAND_EQUIPMENT_BASE_COST = 5	
NDefines.NMilitary.LAND_EQUIPMENT_RAMP_COST = 3				
NDefines.NAI.VARIANT_UPGRADE_MIN_XP = 90
NDefines.NAI.UPGRADE_XP_RUSH_UPDATE = 110 